{
  "hash": "a110319adf40bfe2d3b93ebc553a8cb0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From Samples to Decisions\"\nauthor: \"Will Horne\"\nformat: revealjs\neditor: visual\ncode-fold: true\n---\n\n## Where We Are\n\nWe've learned how to:\n\n-   Compare group averages -- like DMV wait times by neighborhood or voting wait times by race (conditional expectations)\n-   Understand that samples vary (sampling distributions) and that bigger samples = smaller standard errors\n\n. . .\n\n**Today's big question:** How do we use sample data to make *decisions*?\n\n-   Did that job training program *actually* work, or did we just get lucky with our sample?\n-   Is support for Medicaid expansion above 50%?\n-   Do body cameras actually reduce police use of force?\n\n## The Law of Large Numbers\n\nOne of the most useful results in statistics:\n\n. . .\n\n::: callout-tip\n## The Law of Large Numbers (Plain English)\n\nAs you collect more data, your sample average gets closer and closer to the true population average.\n\n**Translation:** Bigger samples = more reliable estimates.\n:::\n\n. . .\n\nThis is why a well-designed survey of 1,500 people can predict election outcomes for 150 million voters + why your agency doesn't need to survey every single citizen.\n\n## Seeing It In Action\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\nWith a small sample, our estimate of average DMV wait time bounces around. As we survey more residents, it settles down near the truth.\n\n## Why the Normal Distribution Keeps Showing Up {.smaller}\n\nImagine your city's 311 system. Individual response times are *skewed* -- most calls get resolved quickly, but some take forever.\n\n. . .\n\nNow imagine running this experiment:\n\n::: incremental\n1.  **Draw a sample** of, say, 50 response times from the full database\n2.  **Calculate the average** of those 50 response times\n3.  **Write it down**, then throw the sample away\n4.  **Repeat** this thousands of times, each time with a fresh random sample of 50\n:::\n\n## The Central Limit Theorem\n\n::: callout-tip\n## The Central Limit Theorem (Plain English)\n\nWhen you repeat that experiment many times -- drawing a sample and computing its average -- the *distribution of those averages* follows a bell curve, **even if the raw data is skewed**.\n\nThe bigger each sample, the more bell-shaped the averages become.\n:::\n\n. . .\n\nThis is what makes hypothesis testing work. Every t-test, every confidence interval we'll compute relies on the sampling distribution being approximately normal -- and the CLT is why that's a safe assumption.\n\n## The CLT In Action\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\nLeft: the raw data is skewed. Middle & right: we drew 5,000 samples and computed each sample's average. **Bigger samples → the averages look more and more like a bell curve.**\n\n## The Practical Takeaway\n\n::: callout-important\n## What This Means For You\n\n1.  **Bigger samples** give you more reliable estimates (LLN)\n2.  **Sample averages** follow a predictable pattern—the normal distribution (CLT)\n3.  Because of #2, we can use **statistical tests** to make decisions about policy effectiveness\n:::\n\n. . .\n\n**Next up:** How do we turn this into a formal test?\n\n# Hypothesis Testing\n\n## A Classic Example: The Lady Tasting Tea\n\n::: incremental\n-   In the 1920s, a biologist named Muriel Bristol claimed she could tell whether tea or milk was added first to a cup\n\n-   Statistician R.A. Fisher was skeptical, so he designed a test:\n\n    -   Make 8 cups of tea, 4 each way\n    -   Present them in random order\n    -   Ask Bristol to identify which 4 had milk added first\n\n-   **She got all 8 correct!**\n\n-   What's the probability of getting all 8 right by pure luck?\n:::\n\n## Could She Just Be Lucky?\n\nIf she was just guessing randomly:\n\n-   There's only **1 way** to pick all 4 correct cups\n-   There are **70 total ways** to pick any 4 cups from 8\n\n. . .\n\n$$P(\\text{all correct by luck}) = \\frac{1}{70} \\approx 0.014 = 1.4\\%$$\n\n. . .\n\n**Conclusion:** A 1.4% chance is pretty small. It's hard to chalk that up to luck -- she probably really could tell the difference.\n\n. . .\n\nThis is the core logic of every hypothesis test: **If nothing were going on, how often would we see results like this?**\n\n## What Is a Hypothesis?\n\nA **hypothesis** is just a statement about a population that we want to test.\n\n. . .\n\n**Policy examples:**\n\n-   Does a job training program increase employment rates?\n-   Is public support for a carbon tax above 50%?\n-   Do body cameras reduce police use of force?\n\n. . .\n\nImportant: we can't *prove* anything with data. We **can** ask how surprising our results would be if there were no real effect.\n\n## The Null and Alternative Hypotheses\n\n::: callout-note\n## The Null Hypothesis (H₀)\n\nThe \"boring\" hypothesis—usually \"no effect\" or \"no difference\"\n\n**Example:** The job training program has no effect on employment\n:::\n\n. . .\n\n::: callout-note\n## The Alternative Hypothesis (H₁)\n\nWhat we're actually interested in—usually \"there IS an effect\"\n\n**Example:** The job training program does affect employment\n:::\n\n. . .\n\nWe test the null hypothesis. If the data would be very surprising under H₀, we **reject** it.\n\n## The Logic of Hypothesis Testing\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\nIf our result falls in the orange \"tails,\" it would be very unlikely under H₀—so we reject it.\n\n## Two Types of Mistakes\n\nWhen we make a decision, we can be wrong in two ways:\n\n|                     | H₀ Actually True | H₀ Actually False    |\n|---------------------|------------------|----------------------|\n| **Don't Reject H₀** | Correct!         | Missed a real effect |\n| **Reject H₀**       | False alarm!     | Correct!             |\n\n. . .\n\n::: callout-warning\n## Key Terms\n\n-   **Type I Error (False Positive):** We said there's an effect, but there isn't\n-   **Type II Error (False Negative):** We missed a real effect\n:::\n\n## Statistical Power: Can We Detect What Matters?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Power {.smaller}\n\n-   **Power** is the probability of *correctly* detecting a real effect (avoiding a Type II error)\n-   Low power = you might miss a program that actually works\n-   Power depends on: **(1)** sample size, **(2)** effect size, **(3)** significance level\n-   Rule of thumb: **80% power** is the minimum standard. Many policy studies are underpowered!\n\n. . .\n\n**Example:** Your city pilots body cameras with 20 officers. Even if cameras truly reduce complaints by 15%, a sample this small has only \\~25% power to detect it — meaning you'd likely conclude \"no effect\" and kill a program that actually works. With 200 officers, power jumps above 90%.\n\n## What Determines Power? {.smaller}\n\nPower depends on three things, and they trade off against each other:\n\n. . .\n\n-   **Sample size (n):** More data → narrower sampling distribution → easier to distinguish a real effect from noise. This is the lever you have the most control over.\n-   **Effect size:** Bigger effects are easier to detect. A program that boosts turnout by 8 points is much easier to pick up than one that boosts it by 0.5 points.\n-   **Significance level (α):** If you set a stricter threshold (say α = 0.01 instead of 0.05), you need stronger evidence to reject H₀ — which means you'll miss more real effects. Lower α = fewer false positives, but also lower power.\n\n. . .\n\nThat last point is worth sitting with: **there's a direct tradeoff between false positives and false negatives.** Making it harder to cry wolf (Type I) means you'll also miss more real effects (Type II). You can't minimize both at the same time: the only free lunch is collecting more data.\n\n## A Formula for Power {.smaller}\n\nYou can see all three ingredients in one formula. For comparing two group means (like treatment vs. control):\n\n$$\\text{Power} = \\Phi\\left(\\frac{|\\mu_1 - \\mu_0|}{\\sigma / \\sqrt{n}} - z_{1-\\alpha/2}\\right)$$\n\n. . .\n\nWhere:\n\n::: incremental\n-   $|\\mu_1 - \\mu_0|$ is the **effect size** — how different the two groups really are\n-   $\\sigma / \\sqrt{n}$ is the **standard error** — gets smaller as n grows\n-   $z_{1-\\alpha/2}$ is the **critical value** set by your significance level (1.96 for α = 0.05)\n-   $\\Phi$ is the cumulative distribution function of the standard normal\n    -   It just converts everything to a probability\n:::\n\n. . .\n\nDon't worry about memorizing this. The point is to see the mechanics: bigger effect in the numerator, more data shrinking the denominator, and a stricter α pushing the critical value up.\n\n## The Power–Significance Tradeoff, Visually\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\nMoving the cutoff to the right (stricter α) shrinks the orange area (fewer false positives) but also shrinks the purple area (less power). Same data, same effect.\n\n## OK, So How Do We Actually Run a Test?\n\nWe know what hypotheses are, what errors we can make, and what power means. Now we need to nail down the mechanics:\n\n. . .\n\n1.  **What kind of test?** One-sided or two-sided?\n2.  **What's the test statistic?** (the p-value)\n3.  **What's the decision rule?** (the significance level α)\n\n. . .\n\nLet's take these one at a time.\n\n## One-Sided vs Two-Sided Tests {.smaller}\n\n::: incremental\n-   **Two-sided test:** Does this program have *any* effect? (H₁: τ ≠ 0)\n    -   This is what we almost always use in policy research\n-   **One-sided test:** Does this program *increase* turnout? (H₁: τ \\> 0)\n    -   Only use when you have strong prior reason to test in one direction\n    -   More powerful (easier to reject) but ignores evidence in the other direction\n:::\n\n. . .\n\n**In practice:** Always default to two-sided tests unless you can clearly justify otherwise. Most published policy research uses two-sided tests.\n\n## The p-value: What Does It Actually Mean?\n\n::: callout-tip\n## Definition\n\nThe **p-value** is the probability of getting a result *at least as extreme* as what we observed, *if the null hypothesis were true*.\n:::\n\n. . .\n\n**In plain English:** \"If nothing special was happening, how often would I see data this surprising?\"\n\n. . .\n\n-   **Small p-value** (like 0.01) → \"This would be rare if H₀ were true\" → Evidence against H₀\n-   **Large p-value** (like 0.45) → \"This could easily happen if H₀ were true\" → Not much evidence against H₀\n\n## What p-values Are NOT\n\n::: callout-warning\n## Common Misconceptions\n\n**A p-value is NOT:**\n\n-   The probability that H₀ is true\n-   The probability that H₁ is true\n-   A measure of how big or important the effect is\n-   A guarantee that your result is meaningful\n:::\n\n. . .\n\n**A p-value of 0.03 does NOT mean \"there's a 3% chance this is a fluke.\"**\n\nIt means: \"If there were no real effect, we'd see data this extreme about 3% of the time.\"\n\n## The 0.05 Threshold {.smaller}\n\nBy convention, researchers often use **α = 0.05** as a cutoff:\n\n-   If p \\< 0.05 → \"Statistically significant\" → Reject H₀\n-   If p ≥ 0.05 → \"Not statistically significant\" → Don't reject H₀\n\n. . .\n\n::: callout-warning\n## Important Caveats\n\n-   The 0.05 threshold is **arbitrary**—there's nothing magical about it\n-   A p-value of 0.049 isn't fundamentally different from 0.051\n-   \"Not significant\" ≠ \"No effect\"—you might just need more data\n-   Always consider the **practical significance**, not just statistical significance\n:::\n\n. . .\n\nIn policy settings, practical significance often matters more. A program that raises test scores by 0.01 points might be \"statistically significant\" with a large enough sample -- but is it worth funding?\n\n## Testing the Voting Experiment {.smaller}\n\nRemember Gerber, Green & Larimer (2008)? We saw the Neighbors mailer group had higher turnout — but is that a real effect, or did we just get a weird sample?\n\n. . .\n\n**Our hypotheses:**\n\n-   **H₀:** The Neighbors mailer has no effect on turnout (turnout is the same in both groups)\n-   **H₁:** The Neighbors mailer affects turnout (turnout differs between groups)\n\n. . .\n\nLet's work through this in R.\n\n## Step 1: Load the Data {.smaller}\n\nThe actual study had about 99,000 households in the control group and 38,000 in the Neighbors treatment. We have a dataset (`gerber_example.csv`) with one row per household: which group they were in, and whether they voted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the data\nvoting_data <- read_csv(\"gerber_example.csv\")\n\n# What does it look like?\nvoting_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 137,435 x 3\n   household_id group   voted\n          <dbl> <chr>   <dbl>\n 1            1 Control     0\n 2            2 Control     1\n 3            3 Control     1\n 4            4 Control     0\n 5            5 Control     0\n 6            6 Control     0\n 7            7 Control     0\n 8            8 Control     1\n 9            9 Control     0\n10           10 Control     1\n# i 137,425 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\nEach row is a household. `voted` = 1 means they turned out; 0 means they didn't.\n\n## Step 2: Look at the Group Means {.smaller}\n\nBefore running any test, let's just look at the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute turnout rate by group\nvoting_data |>\n  group_by(group) |>\n  summarize(\n    n = n(),\n    turnout_rate = mean(voted),\n    se = sd(voted) / sqrt(n())\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 4\n  group         n turnout_rate      se\n  <chr>     <int>        <dbl>   <dbl>\n1 Control   99217        0.296 0.00145\n2 Neighbors 38218        0.376 0.00248\n```\n\n\n:::\n:::\n\n\n. . .\n\nOK, so the turnout rates look different. But there's always some random variation in data — maybe we just got unlucky? That's what the t-test will tell us.\n\n## Step 3: Run the Hypothesis Test {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-sample t-test: does turnout differ by group?\nresult <- t.test(voted ~ group, data = voting_data)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  voted by group\nt = -27.794, df = 65874, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Control and group Neighbors is not equal to 0\n95 percent confidence interval:\n -0.08539512 -0.07414452\nsample estimates:\n  mean in group Control mean in group Neighbors \n              0.2959170               0.3756868 \n```\n\n\n:::\n:::\n\n\n. . .\n\nR gives us a wall of numbers. What do we actually care about?\n\n## Step 4: Reading the Output {.smaller}\n\n**Key numbers to focus on:**\n\n-   **t = -27.79**: The test statistic — how many standard errors the difference is from zero\n-   **p-value = <2e-16**: The probability of seeing a difference this large (or larger) if the mailer had **no effect**\n-   **95% CI: \\[-0.085, -0.074\\]**: The range of plausible values for the true difference in turnout\n-   **Group means: 0.376 (Neighbors) vs 0.296 (Control)**: The actual turnout rates in each group\n\n. . .\n\n**Bottom line:** With a sample this big and a gap this large (\\~8 percentage points), there's essentially no way this is just sampling noise. We reject H₀.\n\n## We Know It's Significant — But How Big Is It?\n\nOK, so the mailer increased turnout. Great. But if you're a campaign manager or an election administrator, \"it worked\" isn't enough — you want to know *how much* it worked, and how confident you should be in that number.\n\n. . .\n\nThis is what **confidence intervals** are for.\n\n# Confidence Intervals\n\n## Beyond Yes/No: Confidence Intervals\n\nHypothesis tests give us a binary answer: reject or don't reject.\n\n. . .\n\nBut often we want to know **how big** an effect is, not just whether it exists.\n\n. . .\n\n::: callout-tip\n## Confidence Interval\n\nA **confidence interval** gives us a range of plausible values for the true population parameter.\n\nA 95% CI means: If we repeated this study many times, about 95% of the intervals we'd calculate would contain the true value.\n:::\n\n## Visualizing a Confidence Interval\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\nThe dot is our estimate; the bar shows the range of values for the true level of support that are consistent with our data.\n\n## Calculating Confidence Intervals\n\nThe formula is simple:\n\n$$\\text{CI} = \\text{Estimate} \\pm (\\text{Critical Value}) \\times (\\text{Standard Error})$$\n\n. . .\n\n**For a 95% CI:** Critical value ≈ 1.96 (or about 2)\n\n. . .\n\n**Example:** 57% support Medicaid expansion (sample mean = 0.57), SE = 0.03\n\n-   Lower bound: $0.57 - 1.96 \\times 0.03 = 0.51$\n-   Upper bound: $0.57 + 1.96 \\times 0.03 = 0.63$\n\n**95% CI: \\[0.51, 0.63\\]**\n\n## Interpreting Confidence Intervals\n\n::: callout-important\n## What a 95% CI Means\n\n**Correct:** \"If we repeated this study many times, 95% of the resulting intervals would contain the true population value.\"\n\n**Incorrect:** \"There's a 95% probability the true value is in this interval.\" (The true value is fixed—it either is or isn't in the interval!)\n:::\n\n. . .\n\n**Think of it this way:** The interval tells you what effect sizes you can't rule out given your data.\n\n## CIs and Hypothesis Testing Are Connected {.smaller}\n\nThere's a useful relationship:\n\n-   If a **95% CI does NOT include zero**, the result is statistically significant at α = 0.05\n-   If a **95% CI DOES include zero**, the result is NOT statistically significant\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture6_Revised_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## CIs in R\n\nThe `t.test()` function gives you confidence intervals automatically:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# From our voting experiment\nresult <- t.test(voted ~ group, data = voting_data)\n\n# Extract just the confidence interval\nresult$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.08539512 -0.07414452\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe true difference in turnout between the Neighbors and Control groups is plausibly somewhere between -0.085 and -0.074.\n\n## Your Turn: What Would You Tell the City Council?\n\nA city ran a **body camera pilot** with 150 officers. Results:\n\n-   Officers with cameras received **23% fewer complaints** than those without\n-   t-test: p = 0.03\n-   95% CI for the reduction: \\[3%, 43%\\]\n\n. . .\n\n**The council asks:** \"Should we expand the program citywide?\"\n\n. . .\n\nThink about: What does the p-value tell you? What does the CI add? What *doesn't* this analysis tell you?\n\n## Summary: From Samples to Decisions\n\n::: incremental\n1.  **Samples work** because of LLN and CLT -- this is why polling and program evaluation are possible\n\n2.  **Hypothesis testing** asks: \"Could this result be random noise?\" (like the Gerber et al. voting experiment)\n\n3.  **p-values** tell you how rare your result would be under the null -- NOT the probability the null is true\n\n4.  **Confidence intervals** give a range of plausible effect sizes -- much more useful than just \"significant\" or \"not\"\n:::\n\n## Looking Ahead\n\nSo far we can compare two groups (t-tests) and quantify uncertainty (CIs). (More than two groups is an easy extension)\n\n. . .\n\nBut what if we want to:\n\n-   Ask whether higher per-pupil **spending** predicts better **graduation rates**?\n-   **Control for** the fact that wealthier districts spend more AND have other advantages?\n-   Include **multiple predictors** at once?\n\n. . .\n\n**Next: Introduction to Regression**: The workhorse tool for quantitative analysis.",
    "supporting": [
      "PADM8410Lecture6_Revised_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}