{
  "hash": "b1703d147f0b1f3019737ee8ba0d7b9a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Difference-in-Differences for Policy Evaluation\"\nauthor: \"Will Horne\"\nformat: revealjs\neditor: visual\ncode-fold: true\nexecute:\n  fig-align: center\n---\n\n## Where We Left Off {.smaller}\n\n::: incremental\n-   Last class, we learned **fixed effects**: control for the unit, use only within-unit variation over time\n\n-   We also saw that **two-way fixed effects** (unit + time) has problems when treatment timing varies across units\n\n-   Today we learn the method that builds directly on those ideas: **Difference-in-Differences (DiD)**\n\n-   DiD is probably the **most commonly used** causal inference tool in applied policy research\n:::\n\n# Part 1: The DiD Idea\n\n## A Story About Cholera {.smaller}\n\n::: incremental\n-   In the 1850s, cholera was killing thousands of people in London. Nobody knew what caused it.\n\n-   The physician John Snow had a theory: cholera spread through contaminated water, not through the air (the prevailing view at the time)\n\n-   Two water companies served overlapping parts of London. In 1852, the **Lambeth Company** moved its water intake upstream, away from the sewage. The other, **Southwark & Vauxhall**, did not.\n\n-   Households served by the two companies lived in the same neighborhoods. The only difference was where their water came from.\n:::\n\n## The Problem: Before-and-After Isn't Enough {.smaller}\n\n::: incremental\n-   After the Lambeth Company moved its pipe, cholera deaths in Lambeth-served households dropped from 130.1 to 84.9 per 10,000 people. That's a decline of 45.2 deaths.\n\n-   Can we conclude that clean water saved 45 lives per 10,000? Not yet.\n\n-   Cholera outbreaks vary from year to year for all sorts of reasons: weather, population density, sanitation practices. Maybe 1854 was just a less severe year overall.\n\n-   **Time is a confounder.** If we only look at one group, we can't separate the effect of the treatment from things that were changing anyway.\n:::\n\n## The Solution: A Comparison Group {.smaller}\n\n::: incremental\n-   Snow had something better than a simple before-and-after comparison. He also had data on households served by **Southwark & Vauxhall**, whose water was still contaminated.\n\n-   If 1854 was simply a better year for cholera, we'd expect deaths to drop in *both* groups.\n\n-   In fact, deaths in the Southwark & Vauxhall areas *rose* from 134.9 to 146.6 per 10,000, an increase of 11.7.\n\n-   So the overall environment was getting *worse* for cholera in 1854, not better. The decline in Lambeth households happened *despite* that trend.\n:::\n\n## Snow's 2×2 Table {.smaller}\n\n| | 1849 (Before) | 1854 (After) | Change |\n|---|---|---|---|\n| **Lambeth** (clean water) | 130.1 deaths per 10,000 | 84.9 | -45.2 |\n| **Southwark & Vauxhall** (contaminated) | 134.9 | 146.6 | +11.7 |\n\n. . .\n\n**Step 1:** The change in the treated group (Lambeth): 84.9 - 130.1 = **-45.2**\n\n. . .\n\n**Step 2:** The change in the control group (Southwark & Vauxhall): 146.6 - 134.9 = **+11.7**\n\n. . .\n\n**Step 3:** The DiD estimate: (-45.2) - (+11.7) = **-56.9 deaths per 10,000**\n\n## What Did We Just Do? {.smaller}\n\n::: incremental\n-   The Lambeth deaths fell by 45.2. But we can't credit all of that to clean water, because other things were changing too.\n\n-   The Southwark & Vauxhall deaths *rose* by 11.7 over the same period. They serve as our benchmark for what would have happened to Lambeth without the clean water.\n\n-   So the true effect of clean water is the Lambeth change *minus* the Southwark & Vauxhall change: -45.2 - 11.7 = -56.9\n\n-   We're not comparing the two groups at one point in time (their levels were similar but not identical). We're comparing how much each group *changed*. That's the \"difference in differences.\"\n:::\n\n## The DiD Formula\n\n$$\\widehat{\\delta}_{DiD} = (\\bar{Y}_{treat}^{post} - \\bar{Y}_{treat}^{pre}) - (\\bar{Y}_{control}^{post} - \\bar{Y}_{control}^{pre})$$\n\n::: {.callout-note}\n## In English\nTake the **change** in the treated group. Subtract the **change** in the control group. What's left is the treatment effect: the part of the change that can't be explained by common time trends.\n:::\n\n## The Key Assumption {.smaller}\n\n::: incremental\n-   This only works if we believe that, **without the treatment**, Lambeth households would have experienced the same trend as Southwark & Vauxhall households\n\n-   This is called the **parallel trends assumption**, and it is the foundation of every DiD design\n\n-   In Snow's case, it's plausible: the households were in the same neighborhoods, exposed to the same weather and sanitation conditions. The only difference was the water source.\n\n-   We'll spend more time on this assumption later. For now, the point is that DiD requires a credible argument that the two groups were on the same trajectory before treatment.\n:::\n\n## Why Should MPAs Care?\n\n::: incremental\n-   DiD is everywhere in policy evaluation: minimum wage studies, Medicaid expansion, education reforms, environmental regulations\n\n-   If you read policy evaluations, you *will* encounter DiD. If you do evaluation work, you will likely use it.\n\n-   Real applications get more complex than Snow's 2×2 table (multiple time periods, many units, staggered policy adoption), and we'll work through those complications today\n:::\n\n## Today's Roadmap\n\n::: incremental\n1.  **DiD with real data in R**: California's organ donation policy\n2.  **The parallel trends assumption**: when is DiD credible?\n3.  **Event studies**: visualizing effects over time\n4.  **Staggered adoption**: when different units get treated at different times\n5.  **Modern solutions**: new methods that fix problems with classic TWFE\n6.  **Practical advice**: a checklist for credible DiD designs\n:::\n\n# Part 2: DiD With Real Data\n\n## California's Organ Donation Policy {.smaller}\n\n::: incremental\n-   In July 2011, **California** changed how it asked people about organ donation at the DMV\n\n-   Previously, the question was opt-in: \"Would you like to be an organ donor?\" (most people skipped it)\n\n-   California switched to **active choice**: \"Do you wish to register as an organ donor?\" with a required yes or no answer\n\n-   **The question:** Did this change increase organ donation registration rates?\n\n-   We have quarterly data on 27 states from Q4 2010 through Q1 2012. Only California changed its policy.\n:::\n\n## Loading the Data {.smaller}\n\nThis example comes from Kessler and Roth (2014) and is used in Huntington-Klein's *The Effect*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(fixest)\nlibrary(causaldata)\n\n# Load the data\nod <- organ_donations\n\n# What does it look like?\nhead(od, 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 4\n   State   Quarter  Rate Quarter_Num\n   <chr>   <chr>   <dbl>       <int>\n 1 Alaska  Q42010  0.75            1\n 2 Alaska  Q12011  0.77            2\n 3 Alaska  Q22011  0.77            3\n 4 Alaska  Q32011  0.78            4\n 5 Alaska  Q42011  0.78            5\n 6 Alaska  Q12012  0.79            6\n 7 Arizona Q42010  0.263           1\n 8 Arizona Q12011  0.209           2\n 9 Arizona Q22011  0.226           3\n10 Arizona Q32011  0.250           4\n11 Arizona Q42011  0.235           5\n12 Arizona Q12012  0.259           6\n```\n\n\n:::\n:::\n\n\nEach row is a state-quarter. `Rate` is the organ donation registration rate. California's policy changes in Q3 2011.\n\n## Step 1: Look at the Raw Trends {.smaller}\n\nBefore running any model, plot the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average donation rate: California vs. everyone else\nod_means <- od %>%\n  mutate(group = ifelse(State == \"California\", \"California\", \"Other States\")) %>%\n  group_by(group, Quarter) %>%\n  summarise(avg_rate = mean(Rate), .groups = \"drop\")\n\nggplot(od_means, aes(x = Quarter, y = avg_rate, color = group, group = group)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  geom_vline(xintercept = \"Q32011\", linetype = \"dashed\", color = \"gray40\") +\n  labs(title = \"Organ Donation Rates: California vs. Other States\",\n       x = \"Quarter\", y = \"Donation Rate\", color = \"\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\nLook at what happens after the dashed line. Do the trends diverge? Not really. That's already a hint about what the regression will find. But let's work through the numbers to be sure.\n\n## Step 2: Create the Treatment Variable {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A unit is \"treated\" if it is California AND in the post-treatment period\nod <- od %>%\n  mutate(\n    California = ifelse(State == \"California\", 1, 0),\n    Post = ifelse(Quarter %in% c(\"Q32011\", \"Q42011\", \"Q12012\"), 1, 0),\n    Treated = California * Post\n  )\n\n# Check: how many treated observations?\nod %>% count(California, Post, Treated)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 4\n  California  Post Treated     n\n       <dbl> <dbl>   <dbl> <int>\n1          0     0       0    78\n2          0     1       0    78\n3          1     0       0     3\n4          1     1       1     3\n```\n\n\n:::\n:::\n\n\n`Treated = 1` only for California in Q3 2011 and after. Everything else is a control observation.\n\n## Step 3: The DiD by Hand {.smaller}\n\nJust like we did with Snow's cholera data, let's compute the DiD estimate manually before running a regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average donation rates by group and period\ndid_table <- od %>%\n  mutate(group = ifelse(California == 1, \"California\", \"Other States\"),\n         period = ifelse(Post == 1, \"After\", \"Before\")) %>%\n  group_by(group, period) %>%\n  summarise(avg_rate = mean(Rate), .groups = \"drop\") %>%\n  pivot_wider(names_from = period, values_from = avg_rate) %>%\n  mutate(Change = After - Before)\n\ndid_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 4\n  group        After Before   Change\n  <chr>        <dbl>  <dbl>    <dbl>\n1 California   0.263  0.271 -0.00853\n2 Other States 0.459  0.445  0.0139 \n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The DiD estimate: difference in the changes\ndid_table$Change[did_table$group == \"California\"] -\n  did_table$Change[did_table$group == \"Other States\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.02245897\n```\n\n\n:::\n:::\n\n\n## Step 4: The DiD Regression {.smaller}\n\nNow let's get the same answer from a regression with proper standard errors. This is the same `feols()` syntax from last class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TWFE regression: state fixed effects + quarter fixed effects\ndid_model <- feols(Rate ~ Treated | State + Quarter, data = od)\nsummary(did_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: Rate\nObservations: 162\nFixed-effects: State: 27,  Quarter: 6\nStandard-errors: IID \n         Estimate Std. Error  t value Pr(>|t|) \nTreated -0.022459   0.020497 -1.09573  0.27524 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.021982     Adj. R2: 0.974196\n                 Within R2: 0.009221\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: {.callout-note}\n## Interpretation\nThe coefficient on `Treated` is the DiD estimate, the same number we computed by hand. It's small and not statistically significant. The active-choice policy **did not meaningfully increase** organ donation rates in California relative to the other states. Not every policy works, and DiD is just as useful for showing null effects as positive ones.\n:::\n\n## The Connection to Fixed Effects {.smaller}\n\n::: incremental\n-   The DiD regression is a **two-way fixed effects** model, which you learned last class:\n\n$$Y_{it} = \\alpha_{i} + \\alpha_{t} + \\beta \\cdot \\text{Treated}_{it} + \\epsilon_{it}$$\n\n-   $\\alpha_i$ is a state fixed effect (absorbs level differences between California and other states)\n-   $\\alpha_t$ is a quarter fixed effect (absorbs trends common to all states)\n-   $\\beta$ is the DiD estimate\n\n-   DiD builds directly on fixed effects. The new ingredient is the treatment variable that \"turns on\" for specific units at a specific time.\n:::\n\n## A Famous Example: Card & Krueger (1994) {.smaller}\n\nThe most famous DiD study in economics uses this same logic. In April 1992, **New Jersey** raised its minimum wage. Neighboring **Pennsylvania** did not.\n\n| | Before (Feb 1992) | After (Nov 1992) | Change |\n|---|---|---|---|\n| **New Jersey** (treated) | 20.44 FTE | 21.03 FTE | +0.59 |\n| **Pennsylvania** (control) | 23.33 FTE | 21.17 FTE | -2.16 |\n\n. . .\n\n**DiD Estimate:** (+0.59) - (-2.16) = **+2.76 FTE employees**\n\n. . .\n\nThe minimum wage increase was associated with an *increase* in employment, the opposite of the standard prediction. This is one of the most influential papers in labor economics.\n\n# Part 3: The Parallel Trends Assumption\n\n## The Key Assumption {.smaller}\n\n::: incremental\n-   We introduced this briefly with Snow's data. Now let's dig into it.\n\n-   DiD requires one critical assumption: **without the treatment**, the treated group would have followed the same trend as the control group. This is called the **parallel trends assumption**.\n\n-   In the organ donation example, it means: if California had *not* changed its DMV question, California's donation rate would have changed at the same rate as the other states.\n\n-   This is an assumption about a **counterfactual** that we can never observe. We can check whether trends were parallel *before* the treatment, but the assumption is about what would have happened *after*.\n:::\n\n## Levels vs. Trends {.smaller}\n\n::: {.callout-important}\n## A Common Confusion\n\nParallel trends does **not** require that the groups are at the same level. In the organ donation plot, California's rate was at a different level than the other states. That's fine. What matters is that they were *changing at the same rate*. Similarly, in Snow's data, the Lambeth and non-Lambeth areas had slightly different death rates in 1849, but DiD still works because we're comparing changes, not levels.\n:::\n\n::: incremental\n-   Two cities can have very different crime rates but still have parallel trends if crime is rising (or falling) at the same rate in both\n\n-   If they are changing at different rates before the policy, any post-treatment difference could just be a continuation of that pre-existing divergence\n:::\n\n## Good vs. Bad Parallel Trends {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\nPanel (a): pre-trends are parallel, so the post-treatment gap is plausibly causal. Panel (b): the control group was already converging before treatment, so the \"effect\" may just be a continuation of that pre-existing trend.\n\n## When Is Parallel Trends Plausible? {.smaller}\n\n::: incremental\n-   **More plausible:**\n    -   Units in similar environments (Snow's households were on the same streets; Card & Krueger chose neighboring NJ and PA, not NJ and Alaska)\n    -   Units selected for treatment based on a fixed characteristic, not a trend\n    -   Short time horizons where trends are less likely to diverge\n\n-   **Less plausible:**\n    -   Comparing a booming city to a declining one\n    -   Units that self-selected into treatment based on anticipated trends (e.g., states that expanded Medicaid because their health outcomes were already improving)\n    -   Very long time horizons with structural changes\n:::\n\n## Testing Parallel Trends {.smaller}\n\n::: incremental\n-   We can't prove parallel trends holds, but we can look for evidence against it\n\n-   **Placebo tests in pre-treatment periods:** Run DiD as if treatment happened earlier. If you find \"effects\" before the real treatment, something is wrong.\n\n-   **Event study plots** (which we'll build later) are the standard way to do this. They show the treatment-control difference at each time period. Before treatment, those differences should hover around zero.\n\n-   Finding null pre-treatment effects doesn't *prove* the assumption, but it's reassuring. Finding significant pre-treatment effects is a serious red flag.\n:::\n\n## Anticipation Effects {.smaller}\n\n::: incremental\n-   What if people change behavior **before** the policy takes effect?\n\n    -   Workers might change jobs before a minimum wage increase\n\n    -   Firms might hire ahead of a regulation deadline\n\n-   Anticipation violates the assumption that treatment \"turns on\" at a specific time. It can also make pre-trends look non-parallel even if the design is otherwise sound.\n\n-   **Solution:** Backdate the treatment period or exclude the periods just before treatment\n:::\n\n\n# Part 4: Event Studies\n\n## Beyond a Single Number {.smaller}\n\n::: incremental\n-   Our organ donation DiD gave us one coefficient: the average treatment effect across all post-treatment quarters. But that single number hides a lot.\n\n-   Did the effect appear immediately, or did it take time to materialize?\n\n-   Did it grow, stabilize, or fade over time?\n\n-   And were pre-treatment trends really parallel, or is our design on shaky ground?\n\n-   An **event study** answers all of these by estimating the DiD effect **separately for each time period**\n:::\n\n## How an Event Study Works {.smaller}\n\n::: incremental\n-   Instead of one \"post\" dummy, we create a dummy for each time period relative to treatment\n\n-   The period just before treatment (event time = -1) is the **reference category**, so all effects are measured relative to that point\n\n-   **Pre-treatment coefficients** should hover around zero if parallel trends holds. This is the placebo test we discussed in Part 3.\n\n-   **Post-treatment coefficients** show how the effect unfolds: does it appear immediately? Grow over time? Fade?\n:::\n\n## Event Study: Organ Donation Data {.smaller}\n\nWe can run an event study on the organ donation data we already have.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a California indicator and use Quarter_Num for event time\nod <- od %>%\n  mutate(California = ifelse(State == \"California\", 1, 0))\n\n# Event study: separate coefficient for each quarter × California\n# ref = 3 means Q2 2011 (the quarter before treatment) is the reference\nes_od <- feols(Rate ~ i(Quarter_Num, California, ref = 3) | State + Quarter_Num,\n               data = od)\n\niplot(es_od,\n      xlab = \"Quarter (1 = Q4 2010, 4 = Q3 2011)\",\n      ylab = \"Estimated Effect\",\n      main = \"Event Study: California Organ Donation Policy\")\n```\n\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\nAll coefficients hover near zero, both before *and* after the policy. This confirms what we saw earlier: the active-choice policy had no detectable effect.\n\n## What a Positive Effect Looks Like {.smaller}\n\nTo see how an event study looks when a policy *does* work, we'll simulate data where the treatment effect **grows over time**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(30317)\n\n# 60 units (30 treated, 30 control), 12 years, treatment in year 7\nunit_fes <- tibble(unit = 1:60, unit_fe = rnorm(60, 0, 3))\n\nevent_data <- expand_grid(unit = 1:60, year = 1:12) %>%\n  left_join(unit_fes, by = \"unit\") %>%\n  mutate(\n    treated_unit = ifelse(unit <= 30, 1, 0),\n    event_time = year - 7,\n    # Dynamic treatment effect: grows over time after treatment\n    te = case_when(\n      treated_unit == 0 ~ 0,  # Control units: no effect\n      event_time < 0    ~ 0,  # Before treatment: no effect\n      event_time == 0   ~ 1.5,\n      event_time == 1   ~ 2.5,\n      event_time == 2   ~ 3.2,\n      event_time == 3   ~ 3.5,\n      TRUE              ~ 4.0  # Levels off\n    ),\n    outcome = 50 + unit_fe + 0.5 * year + te + rnorm(n(), 0, 2)\n  )\n```\n:::\n\n\n## The Event Study Regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# i() creates a dummy for each event_time period\n# ref = -1 sets the period before treatment as the reference\nes_model <- feols(\n  outcome ~ i(event_time, treated_unit, ref = -1) | unit + year,\n  data = event_data\n)\n\n# fixest has a built-in event study plot\niplot(es_model,\n      xlab = \"Periods Relative to Treatment\",\n      ylab = \"Estimated Effect\",\n      main = \"Event Study: Simulated Policy With Growing Effect\")\n```\n\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## Reading an Event Study Plot {.smaller}\n\n::: incremental\n-   **Pre-treatment coefficients** (left of 0): they hover around zero with confidence intervals crossing zero. This supports parallel trends.\n\n-   **The jump at time 0**: the immediate treatment effect (about 1.5 points in our simulation)\n\n-   **Post-treatment growth**: the effect increases over time, then levels off around 4 points\n\n-   **Confidence intervals**: if they include zero after treatment, we can't rule out no effect. Here the post-treatment intervals are clearly above zero.\n\n-   Compare this to the organ donation event study: there, the post-treatment coefficients *also* hovered near zero, confirming the null result.\n:::\n\n. . .\n\n::: {.callout-tip}\n## For Your Reports\nEvent study plots are the **standard way** to present DiD results in policy research. They show both the treatment effect and the parallel trends evidence in a single figure. If you do a DiD analysis, include one.\n:::\n\n# Part 5: The Staggered Adoption Problem\n\n## What If Treatment Happens at Different Times? {.smaller}\n\n::: incremental\n-   So far, we've had a clean setup: California changed its policy, the other states didn't, and it all happened at one point in time\n\n-   In practice, policies are often adopted **at different times** by different units\n\n    -   States expanded Medicaid in 2014, 2015, 2016, or not at all\n\n    -   Cities adopted minimum wage increases in different years\n\n    -   Schools implemented new curricula on different schedules\n\n-   This is called **staggered adoption**, and it creates serious problems for classic TWFE\n:::\n\n## Visualizing Staggered Treatment {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\nDifferent states get treated at different times. Who serves as the \"control\" for whom?\n\n## What Comparisons Does TWFE Make? {.smaller}\n\n::: incremental\n-   With staggered adoption, TWFE estimates a single treatment coefficient from a weighted average of **all possible 2×2 comparisons** in the data\n\n-   Some of those comparisons are fine: treated vs. never-treated, or treated vs. not-yet-treated\n\n-   But TWFE also makes **\"forbidden\" comparisons**: it compares **newly-treated units** to **already-treated units**\n\n-   An already-treated unit is being used as a \"control,\" but it's already affected by treatment. If its treatment effect is changing over time, this comparison is contaminated.\n:::\n\n## A Numerical Example {.smaller}\n\nSuppose a job training program is adopted by two states at different times. The true effect is **+2 in year 1** and **+5 by year 2** (it grows as workers gain skills).\n\n| | Year 1 | Year 2 | Year 3 |\n|---|---|---|---|\n| **State A** (treated Year 1) | 50 + **2** = 52 | 50 + **5** = 55 | 50 + **5** = 55 |\n| **State B** (treated Year 2) | 40 | 40 + **2** = 42 | 40 + **5** = 45 |\n\n. . .\n\nThe true effect is positive for everyone. Now let's see what TWFE does when it uses State A as a \"control\" for State B in Year 2.\n\n## The Forbidden Comparison {.smaller}\n\n::: incremental\n-   TWFE asks: when State B gets treated in Year 2, how does it change relative to State A?\n\n-   **State B** goes from 40 to 42: a change of **+2** (the true Year 1 effect)\n\n-   **State A** goes from 52 to 55: a change of **+3** (but this is State A's treatment effect *growing*, not a time trend!)\n\n-   The DiD from this comparison: (+2) - (+3) = **-1**\n\n-   TWFE interprets this as a *negative* treatment effect. But the true effect on State B is +2. The problem is that State A's \"change\" is driven by its own growing treatment effect, not by a common trend.\n:::\n\n## How This Contaminates the Estimate {.smaller}\n\n::: incremental\n-   TWFE averages across all these 2×2 comparisons, including the forbidden ones\n\n-   The clean comparisons (treated vs. never-treated) pull toward the correct answer\n\n-   The forbidden comparisons (newly-treated vs. already-treated) pull in the wrong direction\n\n-   If the forbidden comparisons get enough weight, the overall TWFE estimate can be **too small, zero, or even negative**, even when the true effect is positive for everyone\n\n-   This is the negative weights problem identified by Goodman-Bacon (2021)\n:::\n\n## When Is TWFE Fine? {.smaller}\n\n::: incremental\n-   **TWFE is fine if:**\n    -   Treatment effects are constant over time and across groups\n    -   All units are treated at the same time (the classic 2×2 case)\n    -   You have a \"never-treated\" group and only compare to them\n\n-   **TWFE is problematic if:**\n    -   Treatment effects build up, fade, or vary across cohorts\n    -   You have staggered adoption with no never-treated group\n    -   You suspect dynamic or heterogeneous effects\n\n-   In practice, constant effects are a strong assumption. Most policies take time to work, which means effects change over time. When in doubt, use the newer methods we'll see next.\n:::\n\n# Part 6: Modern Solutions\n\n## The Good News {.smaller}\n\nEconometricians have developed several methods that fix the staggered DiD problem. The two most widely used:\n\n::: incremental\n-   **Callaway and Sant'Anna (2021):** Estimate separate treatment effects for each treatment cohort at each time period, then aggregate. R package: `did`.\n\n-   **Sun and Abraham (2021):** An interaction-weighted event-study estimator that avoids the contamination. Available in `fixest` via `sunab()`.\n\n-   Both approaches share a key idea: **only make \"clean\" comparisons**. Treated units should only be compared to not-yet-treated or never-treated units, never to already-treated units.\n:::\n\n## Simulating Staggered Adoption {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(30317)\n\n# 40 units in 4 groups:\n# 10 treated starting year 5, 10 in year 7, 10 in year 9, 10 never\nstag_unit_fes <- tibble(unit = 1:40, unit_fe = rnorm(40, 0, 2))\n\nstag_data <- expand_grid(unit = 1:40, year = 1:12) %>%\n  left_join(stag_unit_fes, by = \"unit\") %>%\n  mutate(\n    cohort = case_when(\n      unit <= 10 ~ 5,   # Early adopters\n      unit <= 20 ~ 7,   # Middle adopters\n      unit <= 30 ~ 9,   # Late adopters\n      TRUE ~ Inf         # Never treated\n    ),\n    treated = ifelse(year >= cohort, 1, 0),\n    years_treated = pmax(year - cohort, 0),\n    # Dynamic effect: grows with time since treatment (1 + 0.5 per year)\n    true_te = ifelse(is.finite(cohort) & treated == 1,\n                     1 + 0.5 * years_treated, 0),\n    outcome = 50 + unit_fe + 0.3 * year + true_te + rnorm(n(), 0, 1.5)\n  )\n```\n:::\n\n\nThe effect grows over time since treatment. This is exactly the scenario where TWFE breaks.\n\n## Running Both Models {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\n\n# Classic TWFE: one coefficient for all treatment variation\ntwfe_model <- feols(outcome ~ treated | unit + year, data = stag_data)\n\n# Sun & Abraham: only uses clean comparisons\n# sunab() needs a finite number for never-treated units\nstag_data_sa <- stag_data %>%\n  mutate(cohort_sa = ifelse(is.infinite(cohort), 1000, cohort))\n\nsa_model <- feols(outcome ~ sunab(cohort_sa, year) | unit + year,\n                  data = stag_data_sa)\n```\n:::\n\n\n`sunab()` does the heavy lifting: it figures out which comparisons are clean and estimates the effect for each time period relative to treatment, just like our event study earlier.\n\n## TWFE: A Single (Misleading) Coefficient {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(twfe_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: outcome\nObservations: 480\nFixed-effects: unit: 40,  year: 12\nStandard-errors: IID \n        Estimate Std. Error t value   Pr(>|t|)    \ntreated   1.4837   0.245959 6.03229 3.5002e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 1.3903     Adj. R2: 0.782351\n               Within R2: 0.078358\n```\n\n\n:::\n:::\n\n\nTWFE gives us one number for the treatment effect. But we built in an effect that grows over time, so a single number can't capture the full picture. Worse, the forbidden comparisons may be pulling this estimate in the wrong direction.\n\n## Sun & Abraham: The Full Event Study {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\niplot(sa_model,\n      xlab = \"Periods Relative to Treatment\",\n      ylab = \"Estimated Effect\",\n      main = \"Sun & Abraham Event Study (Staggered DiD)\")\n```\n\n::: {.cell-output-display}\n![](PADM8410Lecture13_DiD_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\nThe Sun & Abraham estimator correctly shows pre-treatment coefficients near zero and a growing post-treatment effect. This is what the true data-generating process looks like.\n\n## The Key Takeaway {.smaller}\n\n::: {.callout-important}\n## Reading DiD Papers\nIf you encounter a DiD paper with **staggered treatment** that was published before roughly 2020, the estimates might be unreliable, especially if treatment effects are likely to grow or change over time. Papers using modern methods (Callaway & Sant'Anna, Sun & Abraham, or similar) have addressed this problem. When evaluating research, ask: \"Is treatment staggered? If so, did they use a modern estimator?\"\n:::\n\n# Part 7: Practical Advice\n\n## A Checklist for Credible DiD Designs\n\n::: incremental\n1.  Is there a **clear treatment** and a **clear control group**?\n2.  Is the **treatment timing plausibly exogenous**, not driven by anticipated outcomes?\n3.  Do **pre-treatment trends look parallel**? (Plot them!)\n4.  Are there **anticipation effects** that could blur the treatment timing?\n5.  Is treatment **staggered**? If so, use modern methods.\n6.  How **sensitive** are results to the choice of control group?\n:::\n\n## What DiD Estimates: The ATT {.smaller}\n\n::: incremental\n-   One important detail: DiD does not estimate the average treatment effect for everyone (the ATE). It estimates the **Average Treatment Effect on the Treated (ATT)**.\n\n-   In Card & Krueger, the estimate tells us what the minimum wage increase did **in New Jersey**. It does not tell us what would happen if Pennsylvania also raised its wage, because PA might be different in ways that matter.\n\n-   In a randomized experiment, treatment and control groups are balanced, so the ATE and ATT are the same. In DiD, groups are not randomly assigned, so we can only speak to the effect on the units that were actually treated.\n\n-   This is usually fine for policy evaluation. Legislators want to know: \"Did *our* policy work?\" That's an ATT question.\n:::\n\n## Common Pitfalls\n\n::: incremental\n-   **Confusing levels with trends:** Groups can be at very different levels; what matters is that they *change at the same rate* pre-treatment\n\n-   **Cherry-picking the control group** to manufacture parallel trends\n\n-   **Not clustering standard errors** at the level of treatment assignment\n\n-   **Using classic TWFE with staggered adoption** when effects are dynamic\n\n-   **Ignoring anticipation effects** that shift behavior before the treatment takes effect\n:::\n\n## Readings {.smaller}\n\n::: incremental\n-   **Cunningham, *Causal Inference: The Mixtape***: Excellent chapter on DiD with real-world examples and R code. Freely available online.\n\n-   **Huntington-Klein, *The Effect***: Very intuitive treatment of DiD and event studies. Also freely available.\n\n-   **Callaway & Sant'Anna (2021)**: The key paper on staggered DiD. Technical, but the introduction is accessible.\n\n-   **Goodman-Bacon (2021)**: \"Difference-in-Differences with Variation in Treatment Timing.\" The paper that showed why TWFE breaks with staggered adoption.\n:::\n\n# Wrapping Up\n\n## What We Covered Today {.smaller}\n\n::: incremental\n1.  **The DiD idea**: Snow's cholera data showed us how to use a comparison group to remove common time trends\n2.  **DiD with real data**: walked through California's organ donation policy step by step in R\n3.  **The parallel trends assumption**: the foundation of DiD credibility\n4.  **Event studies**: the standard way to present DiD results and test assumptions\n5.  **Staggered adoption**: why classic TWFE breaks and how to spot the problem\n6.  **Modern solutions**: Sun & Abraham and Callaway-Sant'Anna fix the staggered problem\n7.  **Practical advice**: a checklist for credible designs\n:::\n\n## What's Next\n\n::: incremental\n-   **Regression Discontinuity Designs**: exploiting arbitrary cutoffs for causal inference\n\n-   **Instrumental Variables**: finding exogenous sources of variation\n:::\n\n## For Your Capstone\n\n::: {.callout-tip}\n## Think About This Now\nIs there a **policy change** in your area of interest with a natural control group? A state that changed a law while a neighbor didn't? A program that was rolled out in some districts before others? If so, DiD might be the right tool, and now you know the modern best practices for using it.\n:::\n",
    "supporting": [
      "PADM8410Lecture13_DiD_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}